# Generated by Django 5.2.16 on 2026-07-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='identificador externo')),
                ('transaction_date', models.DateTimeField(db_index=True, verbose_name='data da transação')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor')),
                ('category', models.CharField(choices=[('FOOD', 'Alimentação'), ('TRANSPORT', 'Transporte'), ('HEALTH', 'Saúde'), ('EDUCATION', 'Educação'), ('LEISURE', 'Lazer'), ('HOUSING', 'Moradia'), ('SERVICES', 'Serviços'), ('TRANSFER', 'Transferência'), ('OTHER', 'Outros')], db_index=True, max_length=20, verbose_name='categoria')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito'), ('TRANSFER', 'Transferência'), ('PAYMENT', 'Pagamento')], max_length=20, verbose_name='tipo')),
                ('channel', models.CharField(choices=[('CARD', 'Cartão'), ('PIX', 'Pix'), ('BANK_TRANSFER', 'Transferência bancária'), ('APP', 'Aplicativo'), ('ATM', 'Caixa eletrônico')], db_index=True, max_length=20, verbose_name='canal')),
                ('status', models.CharField(choices=[('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada'), ('PENDING', 'Pendente'), ('REVERSED', 'Estornada')], db_index=True, max_length=20, verbose_name='status')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='estado')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['customer', 'transaction_date'], name='transaction_customer_date_idx'), models.Index(fields=['status', 'transaction_date'], name='transaction_status_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_gt_zero')],
            },
        ),
    ]
